AUTHOR_USERNAME = 'TestAuthor'
USER_USERNAME = 'TestUser'
GROUP_TITLE = 'Тестовая группа'
GROUP_SLUG = 'test-slug'
GROUP_DESCRIPTION = 'Тестовое описание'
POST_TEXT = 'Тестовый текст'
COMMENT_TEXT = 'Тестовый комминтарий'

INDEX_URL_NAME = 'posts:index'
GROUP_LIST_URL_NAME = 'posts:group_list'
PROFILE_URL_NAME = 'posts:profile'
POST_DETAIL_URL_NAME = 'posts:post_detail'
POST_EDIT_URL_NAME = 'posts:post_edit'
POST_CREATE_URL_NAME = 'posts:post_create'
POST_COMMENT_URL_NAME = 'posts:add_comment'
POST_FOLLOW_INDEX_URL_NAME = 'posts:follow_index'
POST_PROFILE_FOLLOW_URL_NAME = 'posts:profile_follow'
POST_PROFILE_UNFOLLOW_URL_NAME = 'posts:profile_unfollow'


INDEX_TEMPLATE = 'posts/index.html'
GROUP_LIST_TEMPLATE = 'posts/group_list.html'
PROFILE_TEMPLATE = 'posts/profile.html'
POST_DETAIL_TEMPLATE = 'posts/post_detail.html'
CREATE_POST = 'posts/create_post.html'
FOLLOW_TEMPLATE = 'posts/follow.html'
